### ISSUE TITLE
Initial project configuration

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/jpeek-maven-plugin#1]
Create initial project configuration

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#3](https://github.com/yegor256/jpeek-maven-plugin/issues/3) is still not solved.

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek-maven-plugin#1` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@paulodamaso 2 puzzles [#6](https://github.com/yegor256/jpeek-maven-plugin/issues/6), [#7](https://github.com/yegor256/jpeek-maven-plugin/issues/7) are still not solved; solved: [#3](https://github.com/yegor256/jpeek-maven-plugin/issues/3).
