### ISSUE TITLE
Implement jpeek plugin execution JpeekMojo must execute jpeek and analyze project files upon...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek-maven-plugin#3]
The puzzle `1-34fd3cb7` from #1 has to be resolved: 

https://github.com/yegor256/jpeek-maven-plugin/blob/af7ff65372f514e13e9e49af9af1aae4e473e7e2/src/main/java/org/jpeek/plugin/JpeekMojo.java#L36-L39

The puzzle was created by Paulo Lobo on 08-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/jpeek-maven-plugin/issues/3#issuecomment-626673096))

@paulodamaso Job [#3](https://github.com/yegor256/jpeek-maven-plugin/issues/3) is already in scope

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek-maven-plugin/issues/3#issuecomment-626759588))

@paulodamaso This is what I know about this job in C7JGJ00DP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#3](https://github.com/yegor256/jpeek-maven-plugin/issues/3) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek-maven-plugin%233%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat elect

**Comment by 0crat** [comment]
The job [#3](https://github.com/yegor256/jpeek-maven-plugin/issues/3) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f0813591-8f85-45a0-a2dc-df4c09def7b5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #4 to be merged

**Comment by 0pdd** [comment]
The puzzle `1-34fd3cb7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#6](https://github.com/yegor256/jpeek-maven-plugin/issues/6), [#7](https://github.com/yegor256/jpeek-maven-plugin/issues/7) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
