### ISSUE TITLE
Fix rultor release

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/jpeek-maven-plugin#9]
fix rultor release

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/jpeek-maven-plugin/issues/9#issuecomment-631071314))

@paulodamaso The job [#9](https://github.com/yegor256/jpeek-maven-plugin/issues/9) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/3f904cc5-64de-4b4b-98f1-f823fb7a241f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@rultor release tag is `1.0.0`

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor release tag is `1.0.0`

**Comment by paulodamaso** [comment]
@rultor release tag is `1.0.0`

**Comment by paulodamaso** [comment]
@rultor release tag is `1.0.0`

**Comment by 0crat** [comment]
Job was finished in 6 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
